apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  labels:
    app: k8s-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - name: k8s-app
        image: your-ecr-repo-uri:latest  # This will be updated by CI
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.1"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app
spec:
  selector:
    app: k8s-app
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
