apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-app
    app.kubernetes.io/instance: my-app
  name: myapp-svc
  namespace: my-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-app
  type: ClusterIP
status:
  loadBalancer: {}
